Node Explorer: prompt to add nodes to SSH config file for VSCode remotes list
tailscale-dev/vscode-tailscale pull request #233
Opened 2023-09-22 19:35 UTC by tendstofortytwo

Fixes #217.

2023-09-22 23:13 UTC, tylersmalley commented on src/utils/sshconfig.ts
> +  config.append({ Host, User, HostName: Host });
We will need to update the config if the host is already present.

2023-09-22 23:18 UTC, tylersmalley commented on src/utils/sshconfig.ts
> +        );
```suggestion
        const editHost = await vscode.window.showInformationMessage(
          `The SSH config file specifies a username (${cfgUsername}) for host ${addr} that
          is different from the SSH user configured in the Tailscale extension (${tsUsername}). Would you
          like to update one of them?`,
          'Update extension',
          'Update SSH config',
          'Do nothing'
        );
```

2023-09-22 23:21 UTC, tylersmalley requested changes
Looks great - just a few small suggestions. I think we could further improve the UX by removing the command and always syncing the SSH config when `tailscale.node.openRemoteCode` is run. It's the only thing that needs it, and in almost all situations it will be required.

2023-09-22 23:26 UTC, tylersmalley commented on src/config-manager.ts
> +  savedInSSHConfig?: boolean;
I tend to prefer the intention here, something like `persistToSSHConfig`

2023-09-22 23:29 UTC, tylersmalley commented on src/config-manager.ts
> +  differentUserFromSSHConfig?: boolean;
I tend to prefer the intention here, something like `persistToSSHConfig`

2023-09-22 23:29 UTC, tylersmalley commented on src/config-manager.ts
> +  savedInSSHConfig?: boolean;
I tend to prefer the intention here, something like `persistToSSHConfig`

2023-09-22 23:37 UTC, tylersmalley commented
One thing we have to figure out is how someone would change their selection if they choose to use a different SSH user. One thought is to have a context menu item that is only displayed if that setting is used - we could accomplish that with pattern matching on the context. So, in the event they choose to use the SSH config user, they would have a context button for "Update SSH config user" (wording could be improved)

2023-09-25 14:57 UTC, tendstofortytwo commented
My thoughts there were that once the user decouples their Tailscale SSH user from the one in the SSH config file, the one in the config file is no longer our business - we use the user in the Tailscale settings to connect anyway.

2023-09-25 15:00 UTC, tendstofortytwo commented
> Looks great - just a few small suggestions. I think we could further improve the UX by removing the command and always syncing the SSH config when `tailscale.node.openRemoteCode` is run. It's the only thing that needs it, and in almost all situations it will be required.

The reason I added the command was that if you decide not to persist your changes to the SSH config files initially, there is otherwise no way to walk back that decision. Unless we'd prefer not to remember that and prompt the user every time?

2023-09-26 15:27 UTC, tylersmalley commented on src/node-explorer-provider.ts
> +          syncSSHConfig(addr, this.configManager);
Lets await this

2023-09-26 15:28 UTC, tylersmalley approved these changes
Just one small change, then LGTM! This is a huge improvement for the user experience when using open in remote. Great work.

2023-09-26 15:43 UTC, merged